/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113302-g5e751dabc5-20240111"
#endif /* AVUTIL_FFVERSION_H */
